var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function m(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function n(a){if(!(a instanceof Array)){a=m(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={ea:!0},fa={};try{fa.__proto__=ea;da=fa.ea;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function r(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.fa=b.prototype}
function ia(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ka="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function t(a,b){if(b){var c=ka;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}
t("String.prototype.repeat",function(a){return a?a:function(a){var b=ia(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});
t("String.fromCodePoint",function(a){return a?a:function(a){for(var b="",d=0;d<arguments.length;d++){var e=Number(arguments[d]);if(0>e||1114111<e||e!==Math.floor(e))throw new RangeError("invalid_code_point "+e);65535>=e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(e>>>10&1023|55296),b+=String.fromCharCode(e&1023|56320))}return b}});
t("String.prototype.codePointAt",function(a){return a?a:function(a){var b=ia(this,null,"codePointAt"),d=b.length;a=Number(a)||0;if(0<=a&&a<d){a|=0;var e=b.charCodeAt(a);if(55296>e||56319<e||a+1===d)return e;a=b.charCodeAt(a+1);return 56320>a||57343<a?e:1024*(e-55296)+a+9216}}});t("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});
t("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=b[c];if(g===a||Object.is(g,a))return!0}return!1}});t("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==ia(this,a,"includes").indexOf(a,c||0)}});function la(){la=function(){};ka.Symbol||(ka.Symbol=ma)}var ma=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function pa(){la();var a=ka.Symbol.iterator;a||(a=ka.Symbol.iterator=ka.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(aa(this))}});pa=function(){}}function qa(a){pa();a={next:a};a[ka.Symbol.iterator]=function(){return this};return a}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(a){this.a=(k+=Math.random()+1).toString();if(a){a=m(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(){}function d(a){u(a,g)||ja(a,g,{value:new c})}function e(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof c)return a;d(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==
d.get(c)}catch(p){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var k=0;b.prototype.set=function(a,b){d(a);if(!u(a,g))throw Error("WeakMap key fail: "+a);a[g][this.a]=b;return this};b.prototype.get=function(a){return u(a,g)?a[g][this.a]:void 0};b.prototype.has=function(a){return u(a,g)&&u(a[g],this.a)};b.prototype.delete=function(a){return u(a,g)&&u(a[g],this.a)?delete a[g][this.a]:!1};return b});
t("Map",function(a){function b(){var a={};return a.D=a.next=a.head=a}function c(a,b){var c=a.a;return qa(function(){if(c){for(;c.head!=a.a;)c=c.D;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})}function d(a,b){var c=b&&typeof b;"object"==c||"function"==c?g.has(b)?c=g.get(b):(c=""+ ++k,g.set(b,c)):c="p_"+b;var d=a.c[c];if(d&&u(a.c,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||b===e.key)return{id:c,list:d,index:a,u:e}}return{id:c,list:d,
index:-1,u:void 0}}function e(a){this.c={};this.a=b();this.size=0;if(a){a=m(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(m([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||
"t"!=e.value[1]||!d.next().done?!1:!0}catch(q){return!1}}())return a;pa();var g=new WeakMap;e.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.c[c.id]=[]);c.u?c.u.value=b:(c.u={next:this.a,D:this.a.D,head:this.a,key:a,value:b},c.list.push(c.u),this.a.D.next=c.u,this.a.D=c.u,this.size++);return this};e.prototype.delete=function(a){a=d(this,a);return a.u&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.c[a.id],a.u.D.next=a.u.next,a.u.next.D=a.u.D,a.u.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.c={};this.a=this.a.D=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).u};e.prototype.get=function(a){return(a=d(this,a).u)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};e.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=
d.value,a.call(b,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});
t("Set",function(a){function b(a){this.a=new Map;if(a){a=m(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.a.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(m([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=b||g.value[1]!=b)return!1;g=e.next();return g.done||g.value[0]==b||4!=g.value[0].x||
g.value[1]!=g.value[0]?!1:e.next().done}catch(k){return!1}}())return a;pa();b.prototype.add=function(a){a=0===a?0:a;this.a.set(a,a);this.size=this.a.size;return this};b.prototype.delete=function(a){a=this.a.delete(a);this.size=this.a.size;return a};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(a){return this.a.has(a)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return this.a.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.a.forEach(function(d){return a.call(b,d,d,c)})};return b});t("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ia(this,a,"startsWith"),e=b.length,g=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var k=0;k<g&&c<e;)if(b[c++]!=a[k++])return!1;return k>=g}});
function w(a){var b;a.hasAttribute("mark")&&(b=a.getAttribute("mark"));a.hasAttribute("tmark")&&(b=a.getAttribute("tmark"));switch(a.nodeName){case "prolog":return new ra(new sa(a.firstElementChild.textContent));case "version":return new sa(a.textContent);case "pragma":return new ta(a.getAttribute("name"));case "rule":return new y(a.getAttribute("name"),ua(a.children),b);case "alts":return ua(a.children);case "alt":b=new z;a=m(a.children);for(var c=a.next();!c.done;c=a.next())b.add(w(c.value));return b;
case "comment":return va(a);case "literal":return a.hasAttribute("string")?a=new A(a.getAttribute("string"),b):a.hasAttribute("hex")?(a=a.getAttribute("hex"),/^[A-Fa-f0-9]+$/.test(a)||B("literal/@hex in the XML syntax must be a valid hexadecimal number. Provided:'"+a+"'","S06"),a=new wa(a,b)):(B("<literal/> in the XML syntax must have one of @string|@hex"),a=void 0),a;case "insertion":return a.hasAttribute("string")?a=new C(a.getAttribute("string"),!1):a.hasAttribute("hex")?a=new C(a.getAttribute("hex"),
!0):(B("<insertion/> in the XML syntax must have one of @string|@hex"),a=void 0),a;case "inclusion":return xa(a,!1,b);case "exclusion":return xa(a,!0,b);case "member":return ya(a);case "nonterminal":return new D(a.getAttribute("name"),b);case "option":return new za(w(a.firstElementChild),b);case "repeat0":return b=new E(w(a.firstElementChild),b),2==a.children.length&&Aa(b,w(a.children[1])),b;case "repeat1":return b=new Ba(w(a.firstElementChild),b),2==a.children.length&&Aa(b,w(a.children[1])),b;case "sep":return new Ca(w(a.firstElementChild),
b);default:B("Unknown element in ixml tree:"+a.nodeName)}}function ra(a){this.version=a}ra.prototype.f=function(a){var b=a.ownerDocument.createElement("prolog");this.version&&this.version.f(b);a.append(b)};ra.prototype.flat=function(){var a="";this.version&&(a+=this.version.flat());return a};function sa(a){this.version=a;this.a=[]}sa.prototype.f=function(a){var b=a.ownerDocument.createElement("version");b.setAttribute("string",this.version);a.append(b);this.a.forEach(function(a){return a.f(b)})};
sa.prototype.flat=function(){return'ixml version "'+this.version+'".'};function ta(a){this.name=a}ta.prototype.f=function(a){var b=a.ownerDocument.createElement("pragma");b.setAttribute("name",this.name);a.append(b)};ta.prototype.flat=function(){return"["+this.name+"]"};function G(a){this.mark=a;this.a=[];this.G=!1}G.prototype.flat=function(a){return this.mark?this.mark:void 0===a?"":a};G.prototype.f=function(a){this.mark&&a.setAttribute("mark",this.mark)};
function Da(a){var b="";a.a.forEach(function(a){return b+=a.flat()});return b}function y(a,b,c){G.call(this,c);this.name=a;this.definition=b;this.definition.l="| ";this.definition.ba=!1;this.a=[];this.c=null}r(y,G);y.prototype.F=function(a){this.a.push(a)};
y.prototype.f=function(a){var b=a.ownerDocument.createElement("rule");G.prototype.f.call(this,b);b.setAttribute("name",this.name);this.G&&b.setAttributeNS("http://invisiblexml.org/NS","ixml:artifact","true");this.c&&this.c.f(b);this.a.forEach(function(a){return a.f(b)});a.append(b);this.definition.f(b,!0)};y.prototype.s=function(a){this.definition.s(a)};
y.prototype.flat=function(a){var b="\n"+" ".repeat(a-this.name.length)+G.prototype.flat.call(this," ")+this.name+": ";this.a.forEach(function(a){return b+=a.flat()});50<this.definition.flat().length&&(this.definition.l="|\n"+" ".repeat(a+3));return b+this.definition.flat()+". "};function H(a){this.b=a}function va(a){var b=[];a=m(a.childNodes);for(var c=a.next();!c.done;c=a.next())c=c.value,c instanceof Element?b.push(va(c)):b.push(c.textContent);return new H(b)}
H.prototype.f=function(a){var b=a.ownerDocument.createElement("comment");this.b.forEach(function(a){a instanceof H?a.f(b):b.append(new Text(a))});a.append(b)};H.prototype.flat=function(){var a="{";this.b.forEach(function(b){a=b instanceof H?a+b.flat():a+b});return a+"}"};function Ea(a){G.call(this,a);this.l=this.h=null;this.b=[];this.c=[];this.ba=!1}r(Ea,G);f=Ea.prototype;f.add=function(a){this.b.push(a);this.c.push(a)};f.unshift=function(a){this.b.unshift(a);this.c.unshift(a)};f.F=function(a){this.c.push(a)};
function Fa(a,b,c){var d=a.b.indexOf(b);a.b.splice.apply(a.b,[d,1].concat(n(c)));d=a.c.indexOf(b);a.c.splice.apply(a.c,[d,1].concat(n(c)))}f.replace=function(a,b){var c=this.b.indexOf(a);this.b[c]=b;c=this.c.indexOf(a);this.c[c]=b};f.s=function(a,b){var c=this;a(this,b);this.b.forEach(function(b){return b.s(a,c)})};f.display=function(){return"container"};f.f=function(a,b){var c=a;b||(c=a.ownerDocument.createElement(this.h),a.append(c));a=m(this.c);for(b=a.next();!b.done;b=a.next())b.value.f(c,!1)};
f.flat=function(){var a=this;if(1==this.b.length)return this.b[0].flat();var b="";this.c.forEach(function(c,d){b+=c.flat();!(c instanceof H)&&d<a.c.length-1&&(b+=a.l)});return this.ba?"("+b+")":b};function I(){Ea.call(this,null);this.h="alts";this.l="|";this.ba=!0}r(I,Ea);function ua(a){var b=new I;a=m(a);for(var c=a.next();!c.done;c=a.next()){var d=c.value;c=new z;b.add(c);d=m(d.children);for(var e=d.next();!e.done;e=d.next())c.add(w(e.value))}return b}I.prototype.display=function(){return"()"};
function z(){Ea.call(this,null);this.h="alt";this.l=","}r(z,Ea);function J(){I.call(this);this.add(new z)}r(J,I);J.prototype.f=function(a){I.prototype.f.call(this,a,!0)};function M(a,b){G.call(this,b);this.j=a;this.l=null;this.c="";this.a=[];this.m=this.h=null}r(M,G);function Aa(a,b){a.l=b;a.c+="-sep"}f=M.prototype;f.replace=function(a,b){this.j===a&&(this.j=b)};f.C=function(){return[]};f.Y=function(a){return this.C(a,void 0)};f.F=function(a){this.a.push(a)};
function N(a,b){if(a.h)return a.h+b;a.h=a.j instanceof D?a.j.w:"Mult";return a.h+b}f.s=function(a,b){a(this,b);this.j.s(a,this);this.l&&this.l.s(a,this)};f.f=function(a){var b=a;b=a.ownerDocument.createElement(this.m);a.append(b);this.j.f(b);this.a.forEach(function(a){return a.f(b)});this.l&&this.l.f(b)};f.flat=function(a){var b=this.j.flat()+a;this.l?(b+=a,this.a.forEach(function(a){return b+=a.flat()}),b+=this.l.flat()):this.a.forEach(function(a){return b+=a.flat()});return b};
function Ga(a,b){var c=new I;if(a.j instanceof I)a.j.b.forEach(function(a){d=new z;a.b.forEach(function(a){return d.add(a)});d.add(new D(b,null));c.add(d)});else{var d=new z;d.add(a.j);d.add(new D(b,null));c.add(d)}return c}function za(a,b){M.call(this,a,b);this.m="option";this.c="-option"}r(za,M);
za.prototype.C=function(a,b){a=(b?b:N(this,a))+this.c;var c=new I;this.j instanceof I?this.j.b.forEach(function(a){return c.add(a)}):(b=new z,b.add(this.j),c.add(b));b=new z;b.add(new J);c.add(b);a=new y(a,c,"-");a.G=!0;return[a]};za.prototype.flat=function(){return M.prototype.flat.call(this,"?")};function E(a,b){M.call(this,a,b);this.m="repeat0";this.c="-star"}r(E,M);E.prototype.Y=function(a){return this.l?Ha(this,a):this.C(a)};
E.prototype.C=function(a){if(this.l)return Ha(this,a);a=N(this,a)+this.c;var b=Ga(this,a),c=new z;c.add(new J);b.add(c);a=new y(a,b,"-");a.G=!0;return[a]};function Ha(a,b){N(a,b);var c=N(a,b)+"-plus";N(a,b);var d=new Ba(a.j,null);d.l=a.l;c=new za(new D(c,null),null);c.c="-star-sep";var e=c.C(b,N(a,b));d.C(b).forEach(function(a){return e.push(a)});return e}E.prototype.flat=function(){return M.prototype.flat.call(this,"*")};function Ba(a,b){M.call(this,a,b);this.m="repeat1";this.c="-plus"}r(Ba,M);
Ba.prototype.Y=function(a){a=N(this,a)+this.c;var b=this.l,c=new I,d=new z;d.add(this.j);b&&d.add(b.j);d.add(new D(a,null));c.add(d);b=new z;b.add(this.j);c.unshift(b);a=new y(a,c,"-");a.G=!0;return[a]};
Ba.prototype.C=function(a){if(this.l){var b=N(this,a)+this.c,c=N(this,a)+"-star";c=Ga(this,c);var d=new I,e=new z;e.add(this.l.j);e.add(this.j);d.add(e);d=new E(d,null);d.h=this.h;a=d.C(a);b=new y(b,c,"-");b.G=!0;a.unshift(b);return a}b=N(this,a)+this.c;c=N(this,a)+"-star";c=Ga(this,c);a=(new E(this.j,null)).C(a);b=new y(b,c,"-");b.G=!0;a.unshift(b);return a};Ba.prototype.flat=function(){return M.prototype.flat.call(this,"+")};function Ca(a,b){M.call(this,a,b);this.m="sep";this.c="-sep"}r(Ca,M);
Ca.prototype.flat=function(){return this.j.flat()};function P(a){G.call(this,a);this.a=[]}r(P,G);P.prototype.f=function(a){this.mark&&a.setAttribute("tmark",this.mark);this.a.forEach(function(b){return b.f(a)})};P.prototype.F=function(a){this.a.push(a)};P.prototype.s=function(a,b){a(this,b)};P.prototype.matches=function(){return!1};function D(a,b){G.call(this,b);this.w=a;this.b=[];this.a=[]}r(D,G);f=D.prototype;f.s=function(a,b){a(this,b)};f.display=function(){return G.prototype.flat.call(this)+this.w};
f.f=function(a){var b=a.ownerDocument.createElement("nonterminal");G.prototype.f.call(this,b);b.setAttribute("name",this.w);a.append(b);this.a.forEach(function(a){return a.f(b)})};f.flat=function(){return G.prototype.flat.call(this)+this.w+Da(this)};f.F=function(a){this.a.push(a)};function C(a,b){this.a=b;this.text=a;this.value=b?String.fromCodePoint(parseInt(a,16)):a}C.prototype.s=function(a,b){a(this,b)};
C.prototype.display=function(){return"+"+(this.a?"#"+this.text:'"'+this.value.replaceAll('"','""')+'"')};C.prototype.f=function(a){var b=a.ownerDocument.createElement("insertion");b.setAttribute(this.a?"hex":"string",this.text);a.append(b)};C.prototype.flat=function(){return this.display()};function A(a,b){P.call(this,b);this.value=a}r(A,P);A.prototype.matches=function(a){return this.value==a};A.prototype.display=function(){return P.prototype.flat.call(this)+'"'+this.value.replaceAll('"','""')+'"'};
A.prototype.f=function(a){var b=a.ownerDocument.createElement("literal");P.prototype.f.call(this,b);b.setAttribute("string",this.value);a.append(b)};A.prototype.flat=function(){return P.prototype.flat.call(this)+'"'+this.value.replaceAll('"','""')+'"'+Da(this)};function wa(a,b){P.call(this,b);this.text=a;this.c=parseInt(a,16);try{this.value=String.fromCodePoint(this.c)}catch(c){B("encoded character is not a valid Unicode point. Provided:'"+a+"'","S06")}}r(wa,P);
wa.prototype.matches=function(a){return this.c==a.codePointAt(0)};wa.prototype.f=function(a){var b=a.ownerDocument.createElement("literal");P.prototype.f.call(this,b);b.setAttribute("hex",this.text);a.append(b)};wa.prototype.display=function(){return P.prototype.flat.call(this)+"#"+this.text};wa.prototype.flat=function(){return P.prototype.flat.call(this)+"#"+this.text+Da(this)};function Q(a){P.call(this,a);this.b=[];this.c=[];this.h="charset"}r(Q,P);
function xa(a,b,c){b=b?new Ia(c):new Ja(c);a=m(a.children);for(c=a.next();!c.done;c=a.next())b.add(w(c.value));return b}f=Q.prototype;f.add=function(a){this.b.push(a);this.c.push(a)};f.F=function(a){this.c.push(a)};f.s=function(a){this.b.forEach(function(b){return b.s(a)})};f.f=function(a){var b=a.ownerDocument.createElement(this.h);P.prototype.f.call(this,b);a.append(b);a=m(this.c);for(var c=a.next();!c.done;c=a.next())c.value.f(b,!1)};
f.matches=function(a){for(var b=m(this.b),c=b.next();!c.done;c=b.next())if(c.value.matches(a))return!0;return!1};f.display=function(){return"["+this.b.map(function(a){return a.display()}).join(";")+"]"};f.flat=function(){var a=this,b=P.prototype.flat.call(this)+("exclusion"==this.h?"~":"")+"[";this.c.forEach(function(c,d){b+=c.flat();!(c instanceof H)&&d<a.c.length-1&&(b+=";")});return b+="]"+Da(this)};function Ja(a){Q.call(this,a);this.h="inclusion"}r(Ja,Q);
function Ia(a){Q.call(this,a);this.h="exclusion"}r(Ia,Q);Ia.prototype.matches=function(a){return!Q.prototype.matches.call(this,a)};Ia.prototype.display=function(){return"~"+Q.prototype.display.call(this)};function R(){this.c=[];this.a=this.value=null}
function ya(a){if(a.hasAttribute("string"))return new S(a.getAttribute("string"));if(a.hasAttribute("hex"))return new Ka(a.getAttribute("hex"));if(a.hasAttribute("code"))return new La(a.getAttribute("code"));if(a.hasAttribute("from")){var b=a.getAttribute("from");a=a.getAttribute("to");return new Na("#"==b[0]?new Ka(b.substring(1)):new S(b),"#"==a[0]?new Ka(a.substring(1)):new S(a))}B("<member/> in XML syntax must have one of @string|@hex|@code|(@from,@to)")}f=R.prototype;
f.s=function(a,b){a(this,b)};f.display=function(){return this.value};f.F=function(a){this.c.push(a)};f.f=function(a){var b=a.ownerDocument.createElement("member");b.setAttribute(this.a,this.value);a.append(b);this.c.forEach(function(a){return a.f(b)})};f.flat=function(){return this.c.map(function(a){return a.flat()}).join("")};function S(a){R.call(this);this.value=a;this.a="string"}r(S,R);S.prototype.X=function(){return this.value.codePointAt(0)};S.prototype.matches=function(a){return this.value.includes(a)};
S.prototype.flat=function(){return'"'+this.value+'"'+R.prototype.flat.call(this)};S.prototype.Z=function(){return this.value};function Ka(a){R.call(this);this.value=a;this.h=parseInt(a,16);this.a="hex"}r(Ka,R);f=Ka.prototype;f.X=function(){return this.h};f.matches=function(a){return this.h==a.codePointAt(0)};f.display=function(){return this.flat()};f.flat=function(){return"#"+this.value+R.prototype.flat.call(this)};f.Z=function(){return"#"+this.value};
function Na(a,b){R.call(this);(a instanceof S&&1!=a.value.length||b instanceof S&&1!=b.value.length)&&B("The start and end of a charset range must each be exactly one character","S09");this.m=a;this.N=b;this.h=a.X();this.I=b.X();this.I<=this.h&&B("The start character of a charset range must have a code point value less than that of the end","S09")}r(Na,R);Na.prototype.matches=function(a){a=a.codePointAt(0);return this.h<=a&&a<=this.I};Na.prototype.display=function(){return this.flat()};
Na.prototype.f=function(a){var b=a.ownerDocument.createElement("member");b.setAttribute("from",this.m.Z());b.setAttribute("to",this.N.Z());this.c.forEach(function(a){return a.f(b)});a.append(b)};Na.prototype.flat=function(){return this.m.flat()+"-"+this.N.flat()+R.prototype.flat.call(this)};function La(a){R.call(this);this.value=a;try{this.h=new RegExp("\\p{"+a+"}","u")}catch(b){B("'"+a+"' is not a valid Unicode character class","S10")}this.a="code"}r(La,R);La.prototype.matches=function(a){return this.h.test(a)};
La.prototype.flat=function(){return this.value+R.prototype.flat.call(this)};function Oa(a,b,c,d,e,g){this.name=a;this.ended=c>=d.length;this.origin=b;this.position=c;this.o=0;this.b=d;this.index=0;this.U=e;this.a=g;this.source=this.right=this.left=null}f=Oa.prototype;f.K=function(){var a=new Oa(this.name,this.origin,this.position+1,this.b,this.U,this.a);a.o=this.o;return a};function Ra(a,b,c){if(null==c||void 0==c)c=b.position;return a.name==b.name&&a.U==b.U&&a.position==c&&a.origin==b.origin}function U(a){return a.b[a.position]}
function Sa(a){return a.b[a.position]instanceof P||a.b[a.position]instanceof C}f.matches=function(a){var b=this.b[this.position];return b instanceof P&&b.matches(a)};f.V=function(a){var b=this.b[this.position];return b instanceof D&&a.includes(b.w)};function Ta(a){return a.position>=a.b.length}function Ua(a,b,c,d,e){a.source=new Va(b,c,d,e)}
f.display=function(a){var b=this,c="("+this.index+")"+" ".repeat(void 0===a?0:a);c+=this.name+"\u2192";this.b.forEach(function(a,e){c+=(e==b.position?"\u25cf":"")+a.display()+(e<b.b.length-1?",":"")});this.position>=this.b.length&&(c+="\u25cf");return c};
f.f=function(a){function b(b){d=a.ownerDocument.createElement("td");var e=a.ownerDocument.createElement("pre");var k="description sppf";b instanceof Wa&&(k+=" derivation");e.setAttribute("class",k);b&&e.append(new Text(b.display()));d.append(e);c.append(d)}var c=a.ownerDocument.createElement("tr");0==this.origin&&Ta(this)&&c.setAttribute("class","finished");a.append(c);var d=a.ownerDocument.createElement("td");d.append(new Text(""+this.index));c.append(d);d=a.ownerDocument.createElement("td");d.append(new Text(this.U));
c.append(d);d=a.ownerDocument.createElement("td");d.append(new Text(""+this.o));c.append(d);d=a.ownerDocument.createElement("td");d.setAttribute("class","showDot");d.append(new Text(this.display()));c.append(d);d=a.ownerDocument.createElement("td");d.append(new Text(this.origin));c.append(d);d=a.ownerDocument.createElement("td");d.setAttribute("class","description");this.source?d.append(new Text(this.source.display())):d.append(new Text(this.a));c.append(d);b(this.left);b(this.right);return c};
function Xa(a,b){var c="";a.left&&(a.left instanceof Oa||B("left not a state:"+a.left),c+=Xa(a.left,b));a.right&&(c+=Xa(a.right,b));Sa(a)&&"-"!=U(a).mark&&(c+=U(a)instanceof C?U(a).value:Ya(b[a.o]));return c}
f.J=function(a,b,c,d,e,g){function k(d,h){return d?d.J(a,b,c,h,e,g):[]}var h=this.o,x=this.b[this.position-1]?this.b[this.position-1].mark:null,v=k(this.left,x),p=k(this.right,x);if(Ta(this)){h=this.name;d||(d=b.get(h).mark);x=null;g&&!b.get(h).G&&(x=d,d="^");d||(d="^");switch(d){case "^":(new RegExp(/\w(\w|-)*/,"u")).test(h)||B("'"+h+"' is not a valid name for an XML element","D03");var q=a.createElement(h);x&&q.setAttributeNS("http://invisiblexml.org/NS","ixml:mark",x);break;case "@":"xmlns"==h&&
B("'xmlns' is not a valid name for an attribute","D07");q=a.createAttribute(h);h="";h=Xa(this,c);q.value=h;break;case "+":h=this.b[this.position-1].value,Ya(h),q=new Text(h)}if(v instanceof W){var l=new W;if("-"==d){d=m(v.b);for(h=d.next();!h.done;h=d.next())if(x=h.value,p instanceof W){var K=m(p.b);for(h=K.next();!h.done;h=K.next())l.add(x.concat(h.value))}else l.add(x.concat(X(p)));return l}v.b.forEach(function(a){var b=q.cloneNode();if(b instanceof Element)if(p instanceof W){var c=m(p.b);for(b=
c.next();!b.done;b=c.next()){var d=b.value;b=q.cloneNode();Y(a,b,!0);Y(d,b,!0);l.add([b])}}else Y(a,b,!0),Y(p,b,!0),l.add([b]);else l.add(a.concat([b],X(p)))});return l}if(p instanceof W){l=new W;if("-"==d)return p.b.forEach(function(a){return l.add(X(v).concat(a))}),l;p.b.forEach(function(a){var b=q.cloneNode();if(b instanceof Element){var c=[];a.forEach(function(a,b){Array.isArray(a)&&c.push(b)});var d=c.length;if(0<d)for(var e={O:0};e.O<d;e={O:e.O},e.O++)b=q.cloneNode(),Y(v,b,!0),a.forEach(function(a){return function(d,
e){Array.isArray(d)&&c[a.O]!=e||Y(d,b,!0)}}(e)),l.add([b]);else Y(v,b,!0),Y(a,b,!0),l.add([b])}else l.add(X(v).concat([b],a))});return l}switch(d){case "^":return Y(v,q),Y(p,q),[q];case "-":return v.concat(p);default:return[q]}}else{var O=[];Sa(this)&&(d=U(this)?U(this).mark?U(this).mark:"^":"-",U(this)instanceof C?(d=U(this).value,Ya(d),g?(h=a.createElementNS("http://invisiblexml.org/NS","ixml:insertion"),h.setAttribute("string",d),O.push(h)):O.push(new Text(d))):"^"==d&&O.push(new Text(Ya(c[h]))));
if(p instanceof W){l=new W;d=m(p.b);for(h=d.next();!h.done;h=d.next())if(h=h.value,v instanceof W)for(x=m(v.b),K=x.next();!K.done;K=x.next())l.add(K.value.concat(h));else l.add(X(v).concat(h));return l}if(v instanceof W)return l=new W,v.b.forEach(function(a){return l.add(a.concat(X(p),O))}),l;d=v.concat(p);h=0<d.length?d[d.length-1]:null;return O[0]instanceof Text&&h instanceof Text?(h.textContent+=O[0].textContent,d):d.concat(O)}};
function Ya(a){for(var b=m([].concat(n(a))),c=b.next();!c.done;c=b.next())c=c.value.codePointAt(0),(32>c&&![9,10,13].includes(c)||55295<c&&57344>c||65533<c&&65536>c||1114111<c)&&B("Character codepoint "+c+" in '"+a+"' is not a valid XML character","D04");return a}function Wa(a,b,c){this.left=a;this.right=b;this.next=c}
Wa.prototype.display=function(a){a=void 0===a?0:a;var b=" ".repeat(a);b+="DER:";this.left&&(b+=this.left.display(),b+="\n");this.right&&(b+=this.right.display(a+4),b+="\n");this.next&&(b+=" ".repeat(a)+"|OR|"+this.next.display(a+4));return b};
Wa.prototype.J=function(a,b,c,d,e,g){var k=this.left.J(a,b,c,null,e,g);d=this.right?this.right.J(a,b,c,null,e,g):[];if(this.next){var h=new W;d instanceof W?d.b.forEach(function(a){return h.add(X(k).concat(a))}):h.add(X(k).concat(X(d)));if(e)return h;a=this.next.J(a,b,c,null,!1,g);a instanceof W?a.b.forEach(function(a){return h.add(a)}):h.add(a);return h}return d instanceof W?d:k instanceof W?k:k.concat(d)};
function X(a){a instanceof W&&Array.isArray(a.b[0])&&B("Trying to add arrays in ambiguity:"+a.b[0]);return a instanceof W?a.b:a}function W(){this.b=[]}W.prototype.add=function(a){Array.isArray(a)&&Array.isArray(a[0])&&B("Adding an array to an ambiguity:"+a);this.b.push(a)};function Y(a,b,c){c=void 0===c?!1:c;Array.isArray(a)?a.forEach(function(a){return Za(a,b,c)}):Za(a,b,c)}
function Za(a,b,c){c=void 0===c?!1:c;Array.isArray(a)&&B("Internal error: node is array: "+a);c=c?a.cloneNode(!0):a;c instanceof Attr?(b.hasAttribute(a.name)&&B("Attempt to overwrite an existing attribute @"+c.name+" on element "+b.localName,"D02"),b.setAttributeNode(c)):c instanceof Text?(a=b.lastChild,a instanceof Text?a.textContent+=c.textContent:0<c.textContent.length&&b.append(c)):b.append(c)}
function $a(a,b,c){if(b||c)if(a.left||a.right)if(a.right)Ra(a.left,b)&&c&&a.right&&Ra(a.right,c)||(a.left=new Wa(b,c,new Wa(a.left,a.right,null)),a.right=null);else a:{for(var d=a.left;d;){if(Ra(d.left,b)&&c&&d.right&&Ra(d.right,c))break a;d=d.next}a.left=new Wa(b,c,a.left)}else a.left=b,a.right=c}function Va(a,b,c,d){this.type=a;this.a=b;this.c=c;this.h=d}
Va.prototype.display=function(){var a=this.type+" from ";null!=this.a&&(a+="("+this.a+")");null!=this.c&&(null!=this.a&&(a+=" and "),a+="S("+this.c+")("+this.h+") ");return a};function ab(a,b,c){this.B=[];this.c=a;this.A=b;this.m=c;this.H=c.H;this.h=new Map;this.a=[]}ab.prototype.add=function(a){this.B.push(a);a.index=this.B.length};function bb(a,b){return a.B.some(function(a){return Ra(a,b,a.position+1)})}function cb(a,b){return a.B.some(function(a){return Ra(a,b)})}
function fb(a,b){return a.B.filter(function(a){return Ra(a,b)})[0]}function gb(a,b,c){return a.B.filter(function(a){return a.name==b&&a.ended&&a.origin==c&&(!a.source||"scanned"!=a.source.type)})}ab.prototype.K=function(){return new ab(this.c,this.A+1,this.m)};function hb(a,b){var c=a.H.get(b).definition.b.map(function(a,c){return new Oa(b,0,0,a.b,c,"start rule")});c.forEach(function(b){return a.add(b)});ib(a,b,0);c.forEach(function(b){return a.a.push(b)})}
function ib(a,b,c){if(a.h.has(b))a.h.get(b).add(c);else{var d=new Set;d.add(c);a.h.set(b,d)}}function jb(a,b,c){return a.h.has(b)?a.h.get(b).has(c):!1}function kb(a){if(0==a.a.length)return!1;var b=a.a.shift();Ta(b)?lb(a,b,a.A):(b.b[b.position]instanceof D||b.b[b.position]instanceof J||b.b[b.position]instanceof C||"+"==b.b[b.position].mark)&&pb(a,b,a.A);return!0}function qb(a,b){var c=[];a=m(a.B);for(var d=a.next();!d.done;d=a.next())d=d.value,d.name==b&&Ta(d)&&0==d.origin&&c.push(d);return c}
function rb(a){return a.B.filter(function(a){return Sa(a)})}
function pb(a,b,c){var d=U(b);if(d instanceof J||d instanceof C||"+"==d.mark){var e=b.K();e.o=b.o;Ua(e,"predict",b.index,null,null);if(Ta(e)||"+"==d.mark||d instanceof C)Ua(e,"Apredict/complete",b.index,null,null),$a(e,b,null);cb(a,e)||(a.add(e),a.a.push(e))}else if(d instanceof D){var g=d.w;jb(a,g,b.origin)?g==b.name&&c==b.origin&&b.position==b.b.length?B("Infinite ambiguity with production: "+b.name):(d=gb(a,g,b.origin),0==d.length&&(d=gb(a,g,c).filter(function(a){return a.b[a.position-1]instanceof
C})),d.forEach(function(c){e=b.K();e.o=b.o;Ua(e,"Known state predict/complete",b.index,a.A,c.index);$a(e,b,c);a.add(e);a.a.push(e)})):(ib(a,g,b.origin),a.H.get(g).definition.b.forEach(function(d,h){e=new Oa(g,c,0,d.b,h,"predict from ("+b.index+")");e.o=b.o;Ua(e,"predict",b.index,null,null);h=U(e);if(Ta(e)||h instanceof I)e=e.K(),e.o=b.o,Ua(e,"Bpredict/complete",b.index,null,null),h instanceof I||d instanceof z||d instanceof D||$a(e,b,null);cb(a,e)?(e.index=-fb(a,b).index,Ua(e,"Known state predict",
-b.index,null,null)):a.add(e);a.a.push(e)}))}}function lb(a,b,c){var d=b.name;a.m.R[b.origin].B.forEach(function(e){if(e.V([d],c)&&!bb(a,e)){var g=e.K();g.o=b.o;Ua(g,"complete",b.index,b.origin,e.index);if(cb(a,g)){var k=fb(a,g);$a(k,e,Ra(b,k)?null:b)}else a.add(g),$a(g,e,b);a.a.push(g)}})}function sb(a,b,c,d){var e=!1;d.B.forEach(function(g,k){if(g.matches(c)){e=!0;var h=g.K();g.o=b;h.o=b;Ua(h,"scanned",null,d.A,k+1);$a(h,g,null);a.add(h);a.a.push(h)}});return e}
ab.prototype.display=function(){var a=document.implementation.createDocument("","",null);this.f(a);return a};
ab.prototype.f=function(a){var b=this,c=a.createElement("table");a.append(c);var d=a.createElement("thead");c.append(d);var e=a.createElement("tr");d.append(e);var g=a.createElement("th");g.setAttribute("colspan","5");g.setAttribute("class","stateSpace");e.append(g);e="S("+this.A+"): "+(80<this.c.length?"":this.c.slice(0,this.A).join("")+"\u2022"+this.c.slice(this.A).join(""));if(0<this.A){var k=this.c[this.A-1].codePointAt(0);e+=" char '"+this.c[this.A-1]+"' (codepoint "+k+",#"+(new Number(k)).toString(16)+
")"}g.append(new Text(e));e=a.createElement("tr");d.append(e);d=a.createElement("td");d.setAttribute("colspan","3");e.append(d);var h=a.createElement("tbody");c.append(h);this.B.forEach(function(a){return a.f(h,b.A)})};
function tb(a){var b=this;this.version=1;this.b=[];this.a=[];this.start=null;this.H=new Map;a.forEach(function(a){a instanceof y?ub(b,a):(b.b.push(a),a instanceof ra&&a.version&&(b.version=a.version.version))});this.R=[];this.c=null;this.h=[];this.m={};this.compiled=!1;this.parseTime=this.compileTime=null}function ub(a,b){a.H.has(b.name)&&B("Adding productions for an already-defined non-terminal: "+b.name,"S03");a.a.push(b);a.b.push(b);a.H.set(b.name,b)}f=tb.prototype;
f.V=function(a,b){var c=[];a.s(function(a){a.w&&!b.has(a.w)&&(b.add(a.w),c.push(a.w))});return c};
function vb(a){a.start=a.a[0].name;var b=new Set;a.a.forEach(function(a){return b.add(a.name)});for(var c=new Set,d=m(a.a),e=d.next();!e.done;e=d.next())a.V(e.value,c);c=new Set([].concat(n(c)).filter(function(a){return!b.has(a)}));0<c.size&&B("No production rules for non-terminals: "+[].concat(n(c)).join(","),"S02");if(a.m.ga){var g=wb(a);a=new Set([].concat(n(b)).filter(function(a){return!g.has(a)}));0<a.size&&B("Unreachable production rules for non-terminals: "+[].concat(n(a)).join(","),"S002")}}
function wb(a){var b=new Set,c=a.a[0];b.add(c.name);c=[c.name];for(var d={};0<c.length;)d.P=[],c.forEach(function(c){return function(d){d=a.H.get(d);c.P=c.P.concat(a.V(d,b))}}(d)),c=d.P,d={P:d.P};return b}
f.compile=function(a){a.value&&(a=a.value);var b=performance.now();if(a instanceof SaxonJS.XdmMap){var c=SaxonJS.atom("twRewrites");a=a.containsKey(c)?a.get(c)[0].value:!1}else a=a.hasOwn("twRewrites")?a.twRewrites:!1;vb(this);xb(this);yb(this,a);zb(this);vb(this);this.compileTime=performance.now()-b;this.compiled=!0};
function xb(a){for(var b=[],c=m(a.a),d=c.next();!d.done;d=c.next())d.value.s(function(a,c){c&&a instanceof I&&(c.replace(a,new D("Alt"+b.length,null)),b.push(a))});b.forEach(function(b,c){b=new y("Alt"+c,b,"-");b.G=!0;ub(a,b)})}
function zb(a){a=m(a.a);for(var b=a.next();!b.done;b=a.next())b.value.s(function(a,b){if(a instanceof z){var c=a.b.filter(function(a){return a instanceof A});b=m(c);for(c=b.next();!c.done;c=b.next()){var d=c.value,k=[],h=m(d.value);for(c=h.next();!c.done;c=h.next())k.push(new A(c.value,d.mark));c=a.b.indexOf(d);a.b.splice.apply(a.b,[c,1].concat(n(k)));c=a.c.indexOf(d);a.c.splice.apply(a.c,[c,1].concat(n(k)))}}else if(b&&a instanceof A&&"+"!=a.mark&&1<a.value.length){d=[];k=m(a.value);for(c=k.next();!c.done;c=
k.next())d.push(new A(c.value,a.mark));Fa(b,a,d)}})}function yb(a,b){for(var c=[],d=new Set,e=m(a.a),g=e.next();!g.done;g=e.next())g.value.s(function(a,b){if(a instanceof M){var e=new D(N(a,c.length)+a.c,null);b.replace(a,e);d.has(e.w);c.push(a);d.add(e.w)}});0<c.length&&c.forEach(function(c,d){b?c.Y(d).forEach(function(b){return ub(a,b)}):c.C(d).forEach(function(b){return ub(a,b)})})}function Ab(a,b){a.c=b;a.h=b.split(/\n/)}
function Bb(a,b){for(var c=1,d=1,e=0;e<b;e++)d++,/\n/.test(a.c[e])&&(c++,d=1);return{line:c,L:d}}
f.parse=function(a,b){function c(a){return b instanceof SaxonJS.XdmMap?(a=SaxonJS.atom(a),b.containsKey(a)?b.get(a)[0].value:!1):b.hasOwn(a)?b[a]:!1}function d(a){a.hasAttribute("xmlns:ixml")||a.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:ixml","http://invisiblexml.org/NS")}function e(a){d(a);a.setAttributeNS("http://invisiblexml.org/NS","ixml:state","ambiguous")}function g(a){d(a);a.setAttributeNS("http://invisiblexml.org/NS","ixml:state","version-mismatch")}function k(a){var b=a[0];b instanceof
Attr&&B("An attribute node may not be the final parse result @"+b.name,"D05");b instanceof Text&&B("A text node may not be the final parse result: '"+b.textContent+"'","D06");1<a.length&&B("Multiple nodes may not be the final parse result:"+a.map(function(a){a:{switch(a.nodeType){case Node.ELEMENT_NODE:a="<"+a.tagName+"/>";break a;case Node.ATTRIBUTE_NODE:a="@"+a.name;break a;case Node.TEXT_NODE:a="'"+a.textContent+"'";break a}a=void 0}return a}),"D06")}b=void 0===b?{}:b;this.compiled||B("An IXML grammar must be compiled before being used to parse");
b.value&&(b=b.value);var h="1.0"!=this.version,x=performance.now(),v=[].concat(n(a));Ab(this,a);this.R=[];var p=0,q=new ab(v,p++,this);this.R.push(q);var l=null;hb(q,this.start);var K=!0,O=0;try{for(;K;){if(1E3<O++){B("Looping at start?");break}K=kb(q)}}catch(F){F.message&&"looping in process"!=F.message&&(l=F.message)}var na=q;if(!l)for(var T={},V=0;V<v.length;T={S:T.S},V++){q=new ab(v,p++,this);this.R.push(q);if(!sb(q,V,v[V],na)){p=Bb(this,V);l="Failure at line "+p.line+" column "+p.L+"\nGiven '"+
a[V]+"' (codepoint "+a[V].codePointAt(0)+")\nExpecting one of: ";T.S=new Set;rb(na).forEach(function(a){return function(b){var c=U(b);c instanceof C||a.S.add(c.display()+"("+b.name+")")}}(T));l+=[].concat(n(T.S)).join(", ");l+="\n"+this.h[p.line-1]+"\n";l+=" ".repeat(p.L-1)+"^\n";break}K=!0;O=0;try{for(;K;){if(1E3<O++){B("Looping?");break}K=kb(q)}}catch(F){l=F.message;break}na=q}a=performance.now()-x;T=c("justOne");V=c("suppressMarks");p=[];q=qb(q,this.start);if(!l&&0<q.length){na=1<q.length;var L=
document.implementation.createDocument("","",null);L=document.implementation.createDocument("","",null);try{for(var db=m(q),Ma=db.next();!Ma.done;Ma=db.next()){var oa=Ma.value.J(L,this.H,v,null,T,V);if(oa instanceof W)for(var eb=m(oa.b),Pa=eb.next();!Pa.done;Pa=eb.next()){var Qa=Pa.value;e(Qa[0]);var mb=document.implementation.createDocument("","",null);p.push(mb);k(Qa);mb.append(Qa[0].cloneNode(!0));if(T)break}else{na&&e(oa[0]);h&&g(oa[0]);var nb=document.implementation.createDocument("","",null);
p.push(nb);k(oa);nb.append(oa[0].cloneNode(!0))}if(T)break}}catch(F){F.code?l={code:"string"==typeof F.code?F.code.substring(F.code.indexOf("}")+1):F.code,message:F.message}:l="Possible internal error:"+F.constructor.name+":"+F.message,q=[]}L=p[0]}else if(!l){l="\nEnd of input reached before parse completed.\nExpecting one of:\n    ";var ob=new Set;rb(na).forEach(function(a){var b=U(a);b instanceof C||ob.add(a.name+":"+b.display())});l+=[].concat(n(ob)).join(", ")+"\n"}h={parsed:0<q.length,tree:L,
allTrees:p,states:this.R,parseTime:a,treeTime:performance.now()-x-a,compileTime:this.compileTime};l&&(h.failed=l,h.allTrees=null,x=L=document.implementation.createDocument("","",null),h.tree=x,L=x.createElement("ixml"),x.append(L),d(L),L.setAttributeNS("http://invisiblexml.org/NS","ixml:state","failed"),l.code?(h.failed=l.message,h["error-code"]=l.code,L.setAttributeNS("http://invisiblexml.org/NS","ixml:error-code",l.code),L.append(new Text("\n"+l.message))):L.append(new Text("\n"+l)));return h};
f.flat=function(){for(var a="",b=this.b.reduce(function(a,b){return b instanceof y&&b.name.length>a?b.name.length:a},0),c=m(this.b),d=c.next();!d.done;d=c.next())a+=d.value.flat(b);return a};f.display=function(a){if(a)return this.flat();a=document.implementation.createDocument("","",null);this.f(a);return a};f.f=function(a){var b=a.createElement("ixml");this.start&&b.setAttribute("startTerm",this.start);a.append(b);a=m(this.b);for(var c=a.next();!c.done;c=a.next())c.value.f(b)};
var Eb={compile:function(a,b){a instanceof Document?(a=Cb(a),a.compile(b),b=a):(a=(new Db).parse(a instanceof Node?a.textContent:a),a.compile(b),b=a);return b},parse:function(a){return a instanceof Document?Cb(a):(new Db).parse(a instanceof Node?a.textContent:a)}};window.jwiXML=function(){return Eb};function Fb(){this.m="";this.N=this.a=0;this.h=this.c=1;this.I=null;this.line="";this.ca=null;this.da=[]}f=Fb.prototype;f.aa=function(){this.da.push({offset:this.a,line:this.c,L:this.h})};f.$=function(){var a=this.da.pop();this.a=a.offset;this.c=a.line;this.h=a.L};f.T=function(a){for(;a--;)this.next()};f.g=function(){return this.m.charAt(this.a)};f.M=function(){return this.a<this.N};
f.next=function(){this.a==this.N&&B("End of input");this.a+=1;this.I=this.m.charAt(this.a);this.line+=this.I;/\n/.test(this.I)&&(this.c++,this.h=0,this.line="");this.h++;return this.I};f.matches=function(a){return this.m.substring(this.a).match(a)};f.location=function(){return{line:this.c,L:this.h}};f.v=function(a,b){a!=this.g()&&this.i((void 0===b?"":b)+"Expecting character:'"+a+"', given:'"+this.g()+"' (codepoint "+this.g().codePointAt(0)+")","G000");this.next()};
f.W=function(a,b){b=void 0===b?"":b;a.includes(this.g())||(a=a.split("").map(function(a){return"'"+a+"'"}).join(","),this.i(b+"Expecting one of "+a+" - given:'"+this.g()+"' (codepoint "+this.g().codePointAt(0)+")","G000"));this.next()};f.i=function(a,b){b=void 0===b?"ABCD":b;var c=this.location();a+=".\nNear "+("line "+this.c+", column "+this.h)+".\n";a+=this.ca[c.line-1]+"\n";a+=" ".repeat(c.L-1)+"^\n";B(a,b)};
function B(a,b){var c=void 0===c?null:c;a=new SaxonJS.XError(a,"Q{http://invisiblexml.org/NS}"+(void 0===b?"ABCD":b));c&&(a.ha=c.line);throw a;}function Db(){this.a=null}f=Db.prototype;f.i=function(a,b){this.a.i(a,void 0===b?"G000":b)};f.M=function(){return this.a.M()};f.g=function(){return this.a.g()};f.next=function(){return this.a.next()};f.v=function(a,b){return this.a.v(a,b)};f.W=function(a,b){return this.a.W(a,b)};f.matches=function(a){return this.a.matches(a)};f.aa=function(){this.a.aa()};
f.$=function(){this.a.$()};f.T=function(a){this.a.T(a)};function Gb(a,b){for(var c="",d=a.g();d!=b;)c+=d,a.M()||a.i("Unterminated string "+b+"..."),d=a.next();return c}
f.parse=function(a){var b=performance.now(),c=new Fb;this.a=c;c.m=a;c.N=a.length;c.ca=a.split(/\n/);a.startsWith("\n")&&c.c++;try{var d=Z(this);switch(this.g()){case "i":var e=Hb(this)}if(e){Z(this);var g=new ra(e)}else g=null;g&&d.push(g);for(a=[];this.M();)a.push(Ib(this)),this.M()&&(a=a.concat(Jb(this)));d=d.concat(a);d=d.concat(Z(this));var k=new tb(d);k.parseTime=performance.now()-b;return k}catch(h){if(h instanceof SaxonJS.XError)throw h;this.i(h.message,h.code)}};
function Cb(a){var b=performance.now();a instanceof Document&&"ixml"==a.firstChild.nodeName||B("An ixml grammar in XML format must be supplied as a document-node(element(ixml))");var c=[];a=m(a.firstChild.children);for(var d=a.next();!d.done;d=a.next())c.push(w(d.value));c=new tb(c);c.parseTime=performance.now()-b;return c}
function Z(a,b){b=void 0===b?null:b;for(var c=[],d=a.g();/\s/.test(d);)d=a.next();"{"==d&&(c.push(Kb(a)),Z(a).forEach(function(a){return c.push(a)}));b&&c.forEach(function(a){return b.F(a)});return c}function Jb(a){var b=void 0===b?null:b;var c=a.g();if(/\s|\{/.test(c))return Z(a,b);a.i("Must have whitespace, given: '"+c+"' codepoint("+c.codePointAt(0)+")","S01")}
function Kb(a){var b=[],c="";a.v("{","Invalid comment syntax");for(var d=a.g();"}"!=d;)"{"==d?(""!=c&&b.push(c),b.push(Kb(a)),c="",d=a.g()):(c+=d,a.M()||a.i("Unterminated comment"),d=a.next());""!=c&&b.push(c);a.v("}","Invalid comment syntax");return new H(b)}
function Hb(a){a.aa();var b=a.matches(/ixml/);if(b&&(a.T(b[0].length),/\s|\{/.test(a.g()))){var c=Jb(a);if(b=a.matches(/version/)){a.T(b[0].length);c=c.concat(Jb(a));/'|"/.test(a.g())||a.i("Invalid version declaration","G000");b=Lb(a,a.g());c=c.concat(Z(a));a.v(".","Invalid version declaration. ");var d=new sa(b.value);c.forEach(function(a){return d.a.push(a)});return d}}a.$();return null}
function Mb(a){a.v("[","Invalid pragma syntax. ");var b=Nb(a);var c=a.g();":"==c&&(b+=c,a.next(),b+=Nb(a));a.v("]","Invalid pragma syntax. ");Z(a);return new ta(b)}
function Ib(a){var b=null,c=[],d=a.g();if("["==d){var e=Mb(a);d=a.g()}/@|-|\^/.test(d)&&(b=d,d=a.next(),Z(a).forEach(function(a){return c.push(a)}));d=Nb(a);Z(a).forEach(function(a){return c.push(a)});a.W(":=","Invalid rule syntax. ");Z(a).forEach(function(a){return c.push(a)});var g=Ob(a);a.v(".","Invalid rule syntax. ");var k=new y(d,g,b);e&&(k.c=e);c.forEach(function(a){return k.F(a)});return k}
function Nb(a){var b=a.g();(new RegExp(/\p{L}|_/,"u")).test(b)||a.i("'"+b+"' (codepoint "+b.codePointAt(0)+") is not a valid name character");var c=b;for(b=a.next();/\w|\-/.test(b);)c+=b,b=a.next();return c}function Ob(a){var b=new I,c=a.g(),d;/;|\|/.test(c)?d=new J:d=Pb(a);d&&b.add(d);for(c=a.g();/;|\|/.test(c);)a.next(),Z(a,b),c=a.g(),/;|\|/.test(c)?b.add(new J):(b.add(Pb(a)),Z(a,b),c=a.g());return b}
function Pb(a){var b=new z,c=Qb(a);c&&b.add(c);for(c=a.g();/,/.test(c);)a.next(),Z(a,b),(c=Qb(a))||a.i("Invalid start of term"),b.add(c),c=a.g();return b}
function Qb(a){var b=a.g(),c=null;/@|-|\^|\+/.test(b)&&(c=b,a.next(),Z(a),b=a.g());if("+"==c)return c=a.g(),"#"==c?(a=Rb(a),a=new C(a.text,!0)):(a=Lb(a,c),a=new C(a.value,!1)),a;switch(b){case "(":c&&a.i("No marker permitted on bracketed constructs (factor), given '"+c+"'","S006");a.v("(","Invalid bracketed syntax");Z(a);var d=Ob(a);a.v(")","Invalid bracketed syntax");Z(a);break;case ")":return null;case '"':d=Lb(a,b);break;case "'":d=Lb(a,b);break;case "#":d=Rb(a);break;case "[":d=Sb(a,!1);break;
case "~":a.next();Z(a);d=Sb(a,!0);break;case ".":break;default:d=Nb(a),d=new D(d,null),Z(a,d)}c&&(d instanceof P&&"@"==c&&a.i("The only permitted mark for a terminal is '-', '+' or '^', given '"+c+"'","S04"),"+"!=c||d instanceof P&&!(d instanceof Q)||a.i("The insertion mark '+' is only permitted on quoted or encoded literals","S05"),d.mark=c);b=a.g();var e=!1;switch(b){case "*":d=new E(d,c);e=!0;a.next();break;case "+":d=new Ba(d,c);e=!0;a.next();break;case "?":d=new za(d,c),a.next(),Z(a,d)}e&&(b==
a.g()?(a.next(),Z(a,d),a=new Ca(Qb(a),null),Aa(d,a)):Z(a,d));return d}function Lb(a,b){a.next();var c,d=Gb(a,b);for(c=a.next();c==b;)d+=b,a.next(),d+=Gb(a,b),c=a.next();0==d.length&&a.i("A literal string may not be empty","G00");d.includes("\n")&&a.i("A literal string may not contain a linebreak","S11");b=new A(d,null);Z(a,b);return b}
function Rb(a){var b="";a.v("#","Invalid hex syntax");for(var c=a.g();/[0-9]|[A-F]|[a-f]/.test(c);)b+=c,c=a.next();""==b&&a.i("An encoded character must have one or more hexadecimal digits following the # character","S06");c=parseInt(b,16);var d=c%65536;1114111<c&&a.i("An encoded character must have a hexadecimal value within the Unicode point range","S07");(55296<c&&57343>=c||65534==d||65535==d)&&a.i("An encoded character must not denote a Unicode noncharacter or surrogate code point","S08");try{String.fromCodePoint(c)}catch(e){a.i("An encoded character must have a hexadecimal value within the Unicode point range",
"S0Z7")}b=new wa(b,null);Z(a,b);return b}function Sb(a,b){b=b?new Ia(null):new Ja(null);a.v("[","Invalid set syntax");Z(a,b);var c=Tb(a);if(!c)return c=a.g(),/\]/.test(c)||a.i("No closing square bracket on charset. Provided:'"+c+"'","G00"),a.next(),b;Z(a,c);b.add(c);for(c=a.g();/;|\|/.test(c);)a.next(),Z(a,b),c=Tb(a),b.add(c),Z(a,c),c=a.g();/\]/.test(c)||a.i("No closing square bracket on charset. Provided:'"+c+"'","G00");a.next();Z(a,b);return b}
function Tb(a){var b=a.g();if(/[A-Z]/.test(b)){var c=a.g();b=a.next();/[a-z]/.test(b)&&(c+=b,b=a.next(),/[A-Za-z]/.test(b)&&a.i("A Unicode character category code must match [A-Z][a-z]?. Provided: '"+c+b+"'","S10"));/\s|;|\||\]/.test(b)||a.i("A Unicode character category code must match [A-Z][a-z]?. Provided: '"+c+b+"'","S10");c=new La(c);Z(a,c);return c}c=Ub(a);Z(a,c);b=a.g();return"-"==b?(a.next(),Z(a),(b=Ub(a))||a.i("Missing 'to' character of a character range","G00"),new Na(c,b)):c}
function Ub(a){var b=a.g();if("#"==b){b="";a.v("#","Invalid hex syntax");for(var c=a.g();/[0-9]|[A-F]|[a-f]/.test(c);)b+=c,c=a.next();return new Ka(b)}if('"'==b||"'"==b){b="";c=a.g();for(var d=a.next();d!=c;)b+=d,d=a.next();a.next();return new S(b)}};
